package edu.crabium.android.life;

public  enum Brick{
	NONE, 
	YELLOW, 
	BROWN, 
	PASSPORT, 
	DUCKY, 
	UMBRELLA,
	DARK_CLOUD_X0Y0, 
	DARK_CLOUD_X1Y0, 
	DARK_CLOUD_X2Y0,
	DARK_CLOUD_X0Y1, 
	DARK_CLOUD_X1Y1, 
	DARK_CLOUD_X2Y1,
	SPRINGBOARD_CLOSED, 
	SPRINGBOARD_OPENED_X1, 
	SPRINGBOARD_OPENED_X2
};

